events {}

http {
    server {
        listen 443 ssl;
        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;
        server_name kiteixei.42.fr;
        root /var/www/html;
        index index.php index.html index.htm;
    }
}