events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    server {
        # j'écoute uniquement en HTTPS sur le port 443
        listen 443 ssl;

        # j'autorise seulement TLSv1.2 et TLSv1.3
        ssl_protocols TLSv1.2 TLSv1.3;

        # mon certificat auto-signé généré dans le Dockerfile
        ssl_certificate /etc/nginx/ssl/inception.crt;
        ssl_certificate_key /etc/nginx/ssl/inception.key;

        server_name nsmail.42.fr;

        # les fichiers wordpress sont dans ce dossier
        root /var/www/wordpress;

        index index.php index.html index.htm;

        location / {
            try_files $uri $uri/ /index.php?$args;
        }

        # je renvoie les fichiers php vers wordpress via fastcgi sur le port 9000
        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }
}
