version: '3.8'

services:

  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    restart: always
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception
    expose:
      - "9000"

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    restart: always
    ports:
      - "448:443"
    depends_on:
      - wordpress
    env_file:
      - .env
    volumes:
      - wordpress_data:/var/www/wordpress
    networks:
      - inception

volumes:
  mariadb_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  inception:
    driver: bridge