[www]
; Utilisateur et groupe php-fpm
user = www-data
group = www-data

; Ecoute sur le port 9000 (standard php-fpm)
listen = 9000

; Permissions sur le port
listen.owner = www-data
listen.group = www-data

; Empêche php de vider les variables d'environnement
clear_env = no

; Gestion des processus php-fpm
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Logs des workers vers la sortie principale
catch_workers_output = yes