[www]
; je fais tourner php-fpm avec www-data
user = www-data
group = www-data

; j'écoute sur le port 9000 pour recevoir les requêtes de nginx
listen = 9000

listen.owner = www-data
listen.group = www-data

; je garde les variables d'environnement accessibles dans php
clear_env = no

; gestion dynamique des processus php-fpm
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; je redirige les logs des workers vers la sortie principale
catch_workers_output = yes
